behaviors:
    EnemyAI:
        trainer_type: ppo
        hyperparameters:
            batch_size: 128
            buffer_size: 2048
            learning_rate: 3.0e-4
            beta: 5.0e-4
        network_settings:
            normalize: true
            hidden_units: 256
            num_layers: 2
        max_steps: 300000
        time_horizon: 64
        summary_freq: 5000
        reward_signals:
            extrinsic:
                gamma: 0.99
                strength: 1.0
            gail:
                strength: 0.5
                demo_path: Assets\Demonstrations\EnemyTest_1.demo
        behavioral_cloning:
            strength: 0.5
            demo_path: Assets\Demonstrations\EnemyTest_1.demo
